exclude: 'migrations/'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    # -   id: no-commit-to-branch
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/hija/clean-dotenv
    rev: v0.0.5
    hooks:
    -   id: clean-dotenv
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-blanket-type-ignore
    -   id: python-no-eval
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -  id: codespell
# -   repo: https://github.com/Yelp/detect-secrets
#     rev: v1.4.0
#     hooks:
#     -   id: detect-secrets
#         args: ['--baseline', '.secrets.baseline']
# -   repo: https://github.com/mgedmin/check-manifest
#     rev: "0.49"
#     hooks:
#     -   id: check-manifest
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
    -   id: gitleaks
-   repo: https://gitlab.com/adam-moss/pre-commit-trailer
    rev: v1.1.0
    hooks:
    -   id: add-pre-commit-config-trailer
-   repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: v1.6.26.11
    hooks:
    -   id: actionlint
