version: '3.8'

services:
  django:
    build:
      context: .
      args:
        ENVIRONMENT: development
        DJANGO_VERSION: 4.2.0
    command: pytest
    volumes:
      - .:/code

  sqlalchemy:
    build:
      context: .
      args:
        ENVIRONMENT: development
        SQLALCHEMY_VERSION: 1.3.0
    command: pytest
    volumes:
      - .:/code

  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
    command: mkdocs serve --dev-addr 0.0.0.0:8008
    volumes:
      - ./docs:/app/docs
    ports:
      - 8008:8008
