version: '3.8'

services:
  django:
    build:
      context: .
      args:
        ENVIRONMENT: development
        DJANGO_VERSION: 5.0.4  # TODO verify that it's a supported Django version programmatically
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
      - ENV=development
      # - DJANGO_SETTINGS_MODULE=acquiring.settings
  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
    command: mkdocs serve --dev-addr 0.0.0.0:8008
    volumes:
      - ./docs:/app/docs
    ports:
      - 8008:8008

volumes:
  postgres_data:
